export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_MESSAGES = {
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_PARAMS: "INVALID_PARAMS",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  RFP_NOT_FOUND: "RFP_NOT_FOUND",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export const IDENTIFIER_REGEX =
  /References:\s*<RFP_([a-f0-9-]+)VENDOR_([a-f0-9-]+)@/i;
